on:
  workflow_dispatch:   # run the workflow manually 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel any in-progress runs of this workflow when a new run is triggered on the same ref (branch or tag)

permissions:
  contents: write

env:
  RELEASE: v3.3.0-draft
  
name: bundle
jobs:
  build:
    name: Bundle mimalloc release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        branch: [dev,dev2,dev3]
        os: [windows-latest, macOS-latest, ubuntu-22.04]

    steps:
      # Checkout: https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}
          fetch-tags: true
          fetch-depth: 0

      # Build
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          ./bin/bundle.bat

      - name: Build (Linux, macOS)
        if: runner.os != 'Windows'
        run: |
          ./bin/bundle.sh

      # Release
      - name: Create release
        if: ${{ env.RELEASE != '' && env.RELEASE != 'no' }} 
        run: |
          gh release create ${{ env.RELEASE }} --title "${{ env.RELEASE }}" --draft --notes "auto"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        if: ${{ env.RELEASE != '' && env.RELEASE != 'no' }} 
        run: |
          gh release upload ${{ env.RELEASE }} out/bundle/*.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
